apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        #image: mongo:3.6.5-jessie
        image: mongo:5.0.26-focal
        volumeMounts:
          - name: my-volume
            mountPath: /data/db
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: mongodb

  ports:
    - name: mongoport
      port: 27017
      #nodePort: 30080

  type: ClusterIP